### ISSUE TITLE
Extend to Rnw/LaTeX comments

### ISSUE THREAD

**Issue by srvanderplas** [dokato/todor#13]
todor doesn't search .Rnw files by default when using `todor::todor_project_addin()`. It also doesn't recognize LaTeX comments (e.g. comments prefixed by % instead of #). Right now, I'm using 

> %# TODO: thing

and calling `todor::todor_file("file.Rnw")` to get a list of todos, but it would be nice if it would search all literate documents (Rnw, Rmd, Rhtml) for comments and would also detect comments natively, without the extra # character.

**Comment by dokato** [comment]
Thanks, @srvanderplas for that suggestion. I can add an option for that.
