### ISSUE TITLE
Find markers in end of line comments

### ISSUE THREAD

**Issue by BastiHz** [dokato/todor#17]
Thank you for this really helpful addin. Would it be possible to let if find TODO, FIXME etc. in comments at the end of a line of code? For example here:
`
foo <- broken_function()  # FIXME: Fix this later.
`
Currently this does not work for me.

**Comment by dokato** [comment]
Hi @BastiHz, yeah, I think that sounds like a reasonable idea! I'll give it a try soon :)

**Comment by dokato** [comment]
@BastiHz please check #18. Should be working now, but requires more testing before I merge it to master.

**Comment by BastiHz** [comment]
Looks great and seems to be working fine. Thank you very much.
