### ISSUE TITLE
Find TODO items in Markdown documents by default?

### ISSUE THREAD

**Issue by lwjohnst86** [dokato/todor#23]
Quite a useful package, thanks! Could you make searching for TODO items the default rather than needing to add it as an option? I don't quite understand the rationale for having it *not* be the default.

**Comment by dokato** [comment]
Hi @lwjohnst86, thanks. I'm glad you like TODOr. Hmm... I think you might be right with above. TBH I hardly use Rmds, so it was kinda no-brainer to add this as a very specific usage. I'll change that option to default TRUE in the next patch release.

**Comment by mladencucak** [comment]
Any advance on this? Was just thinking to raise this issue.. :)

**Comment by dokato** [comment]
Sorry guys to keep you waiting. The most recent PR should fix it. So far you can install this amendment from GH only, soon to be also in CRAN version.

**Comment by mladencucak** [comment]
Just to confirm it is working fine for me! Cheers...
