### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by elenazadnepr** [dokato/todor#25]
Hi, 
I love the idea, but it doesn't work for me, I can't see my comments in the markers
<img width="802" alt="image" src="https://user-images.githubusercontent.com/15139862/63089728-6ce7ca00-bf8b-11e9-9cc6-338eaf996c65.png">

**Comment by dokato** [comment]
Hi @elenazadnepr . Sorry to hear that! Are you using addin or calling a todor function?
Addins currently support todoing packages or projects, so for that you need to make sure that you are within a package or some project (right top corner in RStudio shouldn't say none, basically).

Alternatively, you can call `todor::todor_file("file.R")` on your file to check specific script you're interested in.
