### ISSUE TITLE
ignore .R files. only find todo's in .Rmd files

### ISSUE THREAD

**Issue by daaronr** [dokato/todor#26]
With my workflow it's better if I can have it ONLY list todo's in .Rmd files, perhaps even in a limited subset of these. Is this a possible feature?

**Comment by dokato** [comment]
hey @daaronr  sorry for coming back so late. Indeed, there wasn't such option before, as I haven't foreseen that scenario. I addressed that in the latest PR #27. Soon to be merged to master. Please install package from GitHub and set this option:

```r
 options(todor_exclude_r=TRUE)
```

That should do the job.

**Comment by dokato** [comment]
Foro TODOring subset of your Rmd's the easiest way would be perhaps to use `todor_file`
