### ISSUE TITLE
Describe all the options available 

### ISSUE THREAD

**Issue by dokato** [dokato/todor#29]
... eg in the Readme.

Recently quite a lot of options were introduced.

**Comment by earcanal** [comment]
Could you also explain how to use `options()` to set default patterns for _all_ RStudio projects? I'm hoping I can write

    options(todor_patterns = c("FIXME", "TODO", "BOOKMARK" ...))

somewhere so that it becomes the default for all source code.

**Comment by dokato** [comment]
Hey @earcanal so the easiest way to do it is to modify your `.Rprofile`. You can find it for example in:
```
> file.path(getwd(), ".Rprofile")
```
and then you add options with todo patterns. It should be loaded at the beginning of each new Rstudio session.

**Comment by earcanal** [comment]
Perfect. Mine now says

    options(todor_patterns = c("FIXME", "TODO", "BOOKMARK", "SMELL", "NOTE", "REVIEW", "BUG", "DEBT"))
