### ISSUE TITLE
Feature request: add 'exclude renv'

### ISSUE THREAD

**Issue by RobertMyles** [dokato/todor#30]
Hi,

Very useful package, thank you. Just wondering if you could add an 'exclude_renv' similar to the code you have for excluding packrat etc. 
The use case is that I have a local project-specific renv setup with its own cache of libraries, many of which have '#TODO' in their internal code.

If you're busy, I could potentially submit a PR, I might not be able to get around to it for a week or two though (if you agree with the idea, of course!).

Thanks!

**Comment by dokato** [comment]
Hi @RobertMyles, that's a great idea! I'll have a look into that and try to fix it soon.

**Comment by RobertMyles** [comment]
Great, thank you :-)

**Comment by dokato** [comment]
Hey @RobertMyles could you have a look if that does the job? I haven't been using `renv` much, so in my simple tests it worked fine. Maybe there's some use-case I'm not aware of though?

**Comment by RobertMyles** [comment]
Hey @dokato -- absolutely, I'll give it a spin asap. Thanks :-)

**Comment by dokato** [comment]
I merged it, LMK if there's any issues with that

**Comment by RobertMyles** [comment]
Apologies for the delay, @dokato , works like a charm, thank you.
