### ISSUE TITLE
It is possible to capture the output into an object or file?

### ISSUE THREAD

**Issue by munozedg** [dokato/todor#38]
I am thinking of generating a nice current todo list that can be embedded in my readme file for instance.

**Comment by dokato** [comment]
Thanks @munozedg for an interesting idea. Currently, it's difficult to do it with `todor`, but it shouldn't be difficult to introduce such feature. I'll add it to the agenda.

**Comment by FMKerckhof** [comment]
Loving the package! Adding on the idea above - how cool would it be to link this using the git/github integration in RStudio (or with github CLI (https://cli.github.com/manual/gh_issue_create)) to automatically/manually open/close issues based upon certain markers (e.g. FIXME/TODO)

**Comment by mcguinlu** [comment]
Just to chip in, I'd really love if this feature (output markers to a object, with option to print to Markdown format) could be added! 

(And happy to try and implement it via a PR if it's of interest!)

**Comment by dokato** [comment]
hey @munozedg this should work now. From version 0.1.2 you can use argument `output` in `todor` to generate either a markdown report, or get a list with markers.
