### ISSUE TITLE
Search in additional file types

### ISSUE THREAD

**Issue by stefanherzog** [dokato/todor#40]
Hi! I really like this package, very useful!

In some projects (e.g., creating a hugo academic website in RStudio with `blogdown`), I wished `todor` would also search some additional files types, such as `.md`, `.toml`. Would it be possible to extend the types of files `todor` searches by default? Or add a "generic" way to extend the search scope, defined in terms of file endings? Thanks!

**Comment by dokato** [comment]
Thanks @stefanherzog for using TODOr. Yeah, this is something I had in mind for quite some time. I'll add it to the roadmap.

**Comment by dokato** [comment]
Hey @stefanherzog , found some time to add that. Please test it by using `todor_extra` option.

**Comment by stefanherzog** [comment]
@dokato : Works, thanks so much!
