### ISSUE TITLE
Enhancement request: Remove comment syntax from TODO text

### ISSUE THREAD

**Issue by mcguinlu** [dokato/todor#45]
Hi @dokato 

One last thing - sorry for pinging you so much today!

In addition to #44, the one other thing I would love to see in `todor` is for comment syntax to be removed from the TODO text. My main use of the package is to write my thesis, and so most of my TODOs are wrapped in markdown comments (`<!--- --->`), which causes the Marker pane to look very "busy", e.g.:

![Screenshot 2021-05-12 152812](https://user-images.githubusercontent.com/41202585/117993395-9c319380-b337-11eb-8821-2a2662c77cee.jpg)

It would be really amazing if `todor` could filter the comment syntax out when presenting the TODOs in the Markers pane, so as to make the TODOs easier to read (i.e. `<!--- TODO This is an example --->` would present as `[ TODO ] This is an example`, rather than `[ TODO ] <!--- This is an example --->`)

Is this something you would consider? Apologies if you have looked at this before and decided against it!

**Comment by dokato** [comment]
Yes, definitely. In the very first version TODOr supported only code comments (`#`), only after people requested markdown (HTML) comments support, I added them for detection, but honestly, forgot to clean the formatting. I'll update that soon.

**Comment by mcguinlu** [comment]
Amazing - thanks a million @dokato! 😁
