### ISSUE TITLE
TODOr active file

### ISSUE THREAD

**Issue by olivroy** [dokato/todor#57]
Hello ! 

I was wondering if it would be possible to support the active addin when focus is on the console

At line 
https://github.com/dokato/todor/blob/010babcc0314c5721d93a03b59413ce9009e0e6b/R/todor.R#L210

if replaced with 
```r
rstudioapi::getSourceEditorContext()$path
```

it would work.

happy to contribute a PR if you think this is relevant

Edit: Ref https://rstudio.github.io/rstudioapi/reference/rstudio-editors.html

**Comment by dokato** [comment]
Sorry @olivroy to come back so late, I've got quite busy summer. Seems indeed like an easy swap, let me test that more in action what are the consequences.

**Comment by olivroy** [comment]
Any more thoughts? I wouldn't mind opening a PR if you agree

**Comment by dokato** [comment]
Apologies @olivroy for the wait. PR ready: https://github.com/dokato/todor/pull/60 Feel free to look, otherwise I'll merge that soon.

**Comment by dokato** [comment]
Someone made a comment lately that "Find project TODOs" is not exhaustive as some people search for just BUG, or FIXME statements, so I decided to sneak in this change to this PR. I think I tested it and it didn't break my keybindings, but good call, I'll double-check that.

Regarding your request, it's merged in already and I'll push to CRAN soon. Thanks for suggesting it!

**Comment by olivroy** [comment]
Seeet! thank you very much
